AWSTemplateFormatVersion: '2010-09-09'
Description: Fargate backend for Node.js app with ALB, ECR, and CloudWatch Logs

Parameters:
  ProjectName:
    Type: String
    Default: angular-node-app
  NodePort:
    Type: Number
    Default: 3333
  ImageTag:
    Type: String
    Description: The tag of the Docker image to deploy.
    Default: latest

Resources:
  # IAM Role for Fargate tasks to pull images and write logs
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: [ecs-tasks.amazonaws.com] }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: !Sub '${ProjectName}-ecs-execution-secrets'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !ImportValue { 'Fn::Sub': '${ProjectName}:DbSecretArn' }
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*'
                Condition:
                  StringEquals:
                    kms:ViaService: !Sub 'secretsmanager.${AWS::Region}.amazonaws.com'

  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${ProjectName}-alb'
      Scheme: internet-facing
      Subnets:
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PublicSubnetIdA' }
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PublicSubnetIdB' }
      SecurityGroups: [!ImportValue { 'Fn::Sub': '${ProjectName}:AlbSecurityGroupId' }]

  # ALB Listener for HTTPS traffic
  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn:
            Fn::ImportValue: !Sub "${ProjectName}-RegionalCertificateArn"
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref EcsTargetGroup

  # ALB Listener for HTTP to HTTPS redirect
  HttpAlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            Host: '#{host}'
            Path: '/#{path}'
            Query: '#{query}'
            StatusCode: HTTP_301

  # Target Group for the ECS Service
  EcsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${ProjectName}-tg'
      VpcId: !ImportValue { 'Fn::Sub': '${ProjectName}:VpcId' }
      Port: !Ref NodePort
      Protocol: HTTP
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: '/health'
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  # ECS Cluster
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${ProjectName}-cluster'

  # ECS Task Definition
  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ProjectName}-task'
      RequiresCompatibilities: ["FARGATE"]
      NetworkMode: awsvpc
      Cpu: "256" # 0.25 vCPU
      Memory: "512" # 0.5 GB
      ExecutionRoleArn: !Ref EcsTaskExecutionRole
      ContainerDefinitions:
        - Name: !Sub '${ProjectName}-container'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-api:${ImageTag}'
          PortMappings:
            - ContainerPort: !Ref NodePort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/ecs/${ProjectName}'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: 'ecs'
          Secrets:
            - Name: DB_PASSWORD
              ValueFrom: !ImportValue { 'Fn::Sub': '${ProjectName}:DbSecretArn' }
          Environment:
            - Name: DB_HOST
              Value: !ImportValue { 'Fn::Sub': '${ProjectName}:DbEndpointAddress' }
            - Name: DB_PORT
              Value: !ImportValue { 'Fn::Sub': '${ProjectName}:DbEndpointPort' }
            - Name: DB_NAME
              Value: !ImportValue { 'Fn::Sub': '${ProjectName}:DbName' }
            - Name: DB_USER
              Value: !ImportValue { 'Fn::Sub': '${ProjectName}:DbMasterUsername' }
            - Name: NODE_TLS_REJECT_UNAUTHORIZED
              Value: '0'

  # ECS Service
  EcsService:
    Type: AWS::ECS::Service
    DependsOn:
      - AlbListener
    Properties:
      ServiceName: !Sub '${ProjectName}-service'
      Cluster: !Ref EcsCluster
      TaskDefinition: !Ref EcsTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdA' }
            - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdB' }
          SecurityGroups: [!ImportValue { 'Fn::Sub': '${ProjectName}:FargateServiceSecurityGroupId' }]
      LoadBalancers:
        - TargetGroupArn: !Ref EcsTargetGroup
          ContainerName: !Sub '${ProjectName}-container'
          ContainerPort: !Ref NodePort

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}'
      RetentionInDays: 7

  # Security Group for VPC Endpoints (ECR, CloudWatch Logs)
  VpcEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for VPC Endpoints (ECR, CloudWatch Logs)
      VpcId: !ImportValue { 'Fn::Sub': '${ProjectName}:VpcId' }
      SecurityGroupIngress:
        # Allow Fargate tasks to connect to VPC Endpoints on 443
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !ImportValue { 'Fn::Sub': '${ProjectName}:FargateServiceSecurityGroupId' }
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc-endpoint-sg'

  # VPC Endpoint for ECR API - Allows Fargate to pull images without public internet
  EcrApiVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue { 'Fn::Sub': '${ProjectName}:VpcId' }
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.api'
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdA' }
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdB' }
      SecurityGroupIds: [!Ref VpcEndpointSecurityGroup]
      PrivateDnsEnabled: true

  # VPC Endpoint for ECR DKR - Allows Fargate to pull images without public internet
  EcrDkrVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue { 'Fn::Sub': '${ProjectName}:VpcId' }
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.dkr'
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdA' }
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdB' }
      SecurityGroupIds: [!Ref VpcEndpointSecurityGroup]
      PrivateDnsEnabled: true

  # VPC Endpoint for S3 Gateway - Required by ECR DKR endpoint
  S3GatewayVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue { 'Fn::Sub': '${ProjectName}:VpcId' }
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      RouteTableIds: !Split [',', { 'Fn::ImportValue': !Sub '${ProjectName}:PrivateRouteTableIds' }]

  # VPC Endpoint for CloudWatch Logs - Allows Fargate to send logs without public internet
  CloudWatchLogsVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue { 'Fn::Sub': '${ProjectName}:VpcId' }
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs'
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdA' }
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdB' }
      SecurityGroupIds: [!Ref VpcEndpointSecurityGroup]
      PrivateDnsEnabled: true

  # VPC Endpoint for Secrets Manager - Allows Fargate to fetch secrets without public internet
  SecretsManagerVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue { 'Fn::Sub': '${ProjectName}:VpcId' }
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdA' }
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdB' }
      SecurityGroupIds: [!Ref VpcEndpointSecurityGroup]
      PrivateDnsEnabled: true

  # VPC Endpoint for KMS - Required for decrypting secrets fetched from Secrets Manager
  KmsVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue { 'Fn::Sub': '${ProjectName}:VpcId' }
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.kms'
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdA' }
        - !ImportValue { 'Fn::Sub': '${ProjectName}:PrivateSubnetIdB' }
      SecurityGroupIds: [!Ref VpcEndpointSecurityGroup]
      PrivateDnsEnabled: true

Outputs:
  ApiUrl:
    Description: URL of the application API
    Value: !Sub 'https://${ApplicationLoadBalancer.DNSName}'
