AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates Route 53 records for the frontend and backend services.

Parameters:
  ProjectName:
    Type: String
    Default: angular-node-app
  HostedZoneId:
    Type: String
    Description: The Route 53 Hosted Zone ID for the domain.
  FrontendDomainName:
    Type: String
    Default: couplebudget.usee.today
  BackendDomainName:
    Type: String
    Default: api.couplebudget.usee.today

Resources:
  FrontendDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref FrontendDomainName
      Type: A
      AliasTarget:
        # This is a static, well-known Hosted Zone ID for all CloudFront distributions.
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName:
          Fn::ImportValue: !Sub '${ProjectName}:FrontendDistributionDomainName'

  BackendDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref BackendDomainName
      Type: A
      AliasTarget:
        HostedZoneId: { "Fn::ImportValue": !Sub "${ProjectName}:AlbHostedZoneId" }
        DNSName: { "Fn::ImportValue": !Sub "${ProjectName}:AlbDnsName" }
