AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the ECR repository for the backend API.

Parameters:
  ProjectName:
    Type: String
    Default: angular-node-app

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ProjectName}-api'
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-api-repo'
