AWSTemplateFormatVersion: '2010-09-09'
Description: Angular front-end on S3 (private) served by CloudFront (OAC)

Parameters:
  ProjectName:
    Type: String
    Default: angular-node-app
  FrontendCertificateArn:
    Type: String
    Description: ARN of the ACM certificate for CloudFront (must be in us-east-1).
  FrontendDomainName:
    Type: String
    Default: couplebudget.usee.today

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${AWS::AccountId}-fe'
      OwnershipControls:
        Rules: [{ ObjectOwnership: BucketOwnerEnforced }]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration: { Status: Enabled }
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-frontend-bucket'

  CfOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      Name: !Sub '${ProjectName}-oac'
      OriginAccessControlOriginType: s3
      SigningBehavior: always
      SigningProtocol: sigv4

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref FrontendDomainName
        ViewerCertificate: # Must be in us-east-1
          AcmCertificateArn: !Ref FrontendCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: s3-origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref CfOriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: s3-origin
          ViewerProtocolPolicy: redirect-to-HTTPS
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          Compress: true
          ForwardedValues: { QueryString: false }
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        HttpVersion: http2

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal: { Service: cloudfront.amazonaws.com }
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !GetAtt FrontendDistribution.Arn

Outputs:
  FrontendBucketName:
    Value: !Ref FrontendBucket
  FrontendDomain:
    Value: !GetAtt FrontendDistribution.DomainName
    Description: CloudFront domain to serve the Angular app
    Export:
      Name: !Sub '${ProjectName}:FrontendDistributionDomainName'
